import { getWithParams, postJSON } from './request';

export type OpportunityAssessment={id:string;score:number;confidence:number;ruleVersion:string;factors:Record<string,number|null>};
export type ProductSnapshot={id:string;title:string;currency:'EUR';priceCents?:number;availability?:string;brand?:string;images:string[]|null;capturedAt:string};
export type SourceProduct={id:string;source:string;externalId:string;canonicalUrl:string;currentSnapshotId?:string;createdAt:string};
export type ProductListItem=SourceProduct&{currentSnapshot:ProductSnapshot;assessment?:OpportunityAssessment};
export type CursorPage<T>={items:T[];nextCursor?:string;hasMore:boolean;limit:number};
export type CollectionKind='manual'|'search'|'seller'|'rule'|'import';
export type Collection={id:string;name:string;description?:string;kind:CollectionKind;rules?:Record<string,unknown>;createdAt:string};
export type DraftState='DISCOVERED'|'ASSESSED'|'DRAFTING'|'NEEDS_REVIEW'|'READY'|'SCHEDULED'|'PUBLISHING'|'PUBLISHED'|'PAUSED'|'ENDED'|'PUBLISH_FAILED'|'BLOCKED';
export type ListingDraft={id:string;sourceProductId:string;state:DraftState;category?:string;priceCents?:number;currency:'EUR';currentContentVersionId?:string;imageSetId?:string;validationErrors:string[]|null;createdAt:string};
export type ContentVersion={id:string;version:number;title:string;description:string;specifics:Record<string,string>;generator:string;createdAt:string};
export type GPSRProfile={id:string;name:string;manufacturerName:string;manufacturerAddress:string;responsiblePersonName:string;responsiblePersonAddress:string;safetyInformation:string;documentReferences:string[];createdAt:string};
export type EbayCategoryAspect={attrId:string;name:string;required:boolean;valueType?:string;options?:string[];syncedAt?:string};

export const newIdempotencyKey=(action:string)=>`${action}-${Date.now()}-${globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`;
const command=<T>(path:string,body:object,key:string)=>postJSON<T>(path,body,{headers:{'Idempotency-Key':key}});
export const runDiscovery=(url:string,key=newIdempotencyKey('discovery'))=>command<{product:SourceProduct;snapshot:ProductSnapshot;assessment:OpportunityAssessment}>('/v1/discovery-runs',{url},key);
export const listMindBayProducts=(params?:{q?:string;collectionId?:string;minScore?:number;cursor?:string;limit?:number})=>getWithParams<CursorPage<ProductListItem>>('/v1/products',params);
export const listCollections=(params?:{cursor?:string;limit?:number})=>getWithParams<CursorPage<Collection>>('/v1/collections',params);
export const createCollection=(body:{name:string;description?:string;kind:CollectionKind;rules?:Record<string,unknown>},key=newIdempotencyKey('collection'))=>command<Collection>('/v1/collections',body,key);
export const addProductToCollection=(collectionId:string,body:{sourceProductId:string;reason?:string},key=newIdempotencyKey('collection-product'))=>command<{id:string;collectionId:string;sourceProductId:string;reason?:string}>(`/v1/collections/${encodeURIComponent(collectionId)}/products`,body,key);
export const listListingDrafts=(params?:{state?:DraftState;cursor?:string;limit?:number})=>getWithParams<CursorPage<ListingDraft>>('/v1/listing-drafts',params);
export const getListingDraft=(id:string)=>getWithParams<{draft:ListingDraft;versions:ContentVersion[]}>(`/v1/listing-drafts/${encodeURIComponent(id)}`);
export const createListingDraft=(body:{sourceProductId:string;category:string;priceCents:number;requiredSpecifics:string[];specifics:Record<string,string>;imageAssetIds:string[];gpsrProfileId?:string},key=newIdempotencyKey('draft'))=>command<ListingDraft>('/v1/listing-drafts',body,key);
export const generateListing=(id:string,key=newIdempotencyKey('generate'))=>command<ContentVersion>(`/v1/listing-drafts/${encodeURIComponent(id)}/generate`,{},key);
export const validateListing=(id:string,body:{gpsrOverride?:boolean;overrideReason?:string},key=newIdempotencyKey('validate'))=>command<{state:DraftState;errors:string[];gpsrOverridden:boolean}>(`/v1/listing-drafts/${encodeURIComponent(id)}/validate`,body,key);
export const listGPSRProfiles=()=>getWithParams<{items:GPSRProfile[]}>('/v1/gpsr-profiles');
export const createGPSRProfile=(body:{name:string;manufacturerName:string;manufacturerAddress:string;responsiblePersonName:string;responsiblePersonAddress:string;safetyInformation:string;documentReferences:string[]},key=newIdempotencyKey('gpsr-profile'))=>command<GPSRProfile>('/v1/gpsr-profiles',body,key);
export const listEbayCategoryAspects=(categoryId:string)=>getWithParams<{items:EbayCategoryAspect[]}>(`/api/v1/platform/ebay/categories/${encodeURIComponent(categoryId)}/aspects`);
export const syncEbayCategoryAspects=(categoryId:string)=>postJSON<{items:EbayCategoryAspect[];synced:number}>(`/api/v1/platform/ebay/categories/${encodeURIComponent(categoryId)}/aspects/sync`,{});
export type CalendarPreviewSlot={listingDraftId:string;contentVersionId:string;title:string;category:string;scheduledFor:string;score:number;reason:string};
export type CalendarSlot={id:string;listingDraftId:string;contentVersionId:string;scheduledFor:string;status:'DRAFT'|'SCHEDULED'|'HELD'|'PUBLISHING'|'PUBLISHED'|'FAILED'|'CANCELLED';plannerScore:number;plannerReason?:string;publicationJobId?:string;priceCents?:number;currency?:string;jobStatus?:PublicationJob['status'];errorMessage?:string;externalListingId?:string;externalUrl?:string};
export type PublicationJob={id:string;status:'SCHEDULED'|'PUBLISHING'|'PUBLISHED'|'FAILED'|'DRY_RUN';workflowId?:string;scheduledFor:string;errorMessage?:string};
export type PublishConfig={merchantLocationKey:string;paymentPolicyId:string;returnPolicyId:string;fulfillmentPolicyId:string;condition:'NEW'|'USED_EXCELLENT'|'USED_GOOD';quantity:number;productSafetyStatementIds?:string};
export const previewCalendar=(body:{startAt:string;days:number;maxPerDay:number;minSpacingMinutes:number})=>postJSON<{slots:CalendarPreviewSlot[];unplaced:number}>('/v1/calendar/preview',body);
export const applyCalendar=(body:{shopId:string;marketplace:'EBAY_DE';slots:CalendarPreviewSlot[];publishConfig:PublishConfig},key=newIdempotencyKey('calendar-apply'))=>command<{slots:CalendarSlot[];jobs:PublicationJob[]}>('/v1/calendar/apply',body,key);
export const listCalendarSlots=(params?:{from?:string;to?:string})=>getWithParams<{items:CalendarSlot[]}>('/v1/calendar/slots',params);
export const approvePublication=(id:string,key=newIdempotencyKey('publication-approve'))=>command<{listing:null|{id:string;externalListingId:string;externalUrl:string}}>(`/v1/publications/${encodeURIComponent(id)}/approve`,{},key);
export type MarketplaceListing={id:string;listingDraftId:string;publicationJobId:string;marketplace:'ebay';externalListingId:string;externalOfferId:string;externalUrl?:string;sku:string;status:string;priceCents:number;currency:'EUR'};
export type PriceRule={id:string;name:string;version:number;minMarginBasisPoints:number;targetMarginBasisPoints:number;maxPriceCents?:number;maxDeltaCents:number;maxDeltaBasisPoints:number;cooldownSeconds:number;platformFeeBasisPoints:number;shippingCents:number;reserveCents:number;autoApply:boolean;createdAt:string};
export type PriceDecisionOutcome='NO_CHANGE'|'PROPOSED'|'AUTO_APPLIED'|'BLOCKED_MARGIN'|'BLOCKED_POLICY'|'BLOCKED_COOLDOWN';
export type PriceDecision={id:string;marketplaceListingId:string;monitorRunId:string;priceRuleId:string;ruleVersion:number;oldPriceCents:number;targetPriceCents:number;landedCostCents:number;expectedFeeCents:number;expectedMarginCents:number;expectedMarginBasisPoints:number;outcome:PriceDecisionOutcome;autoEligible:boolean;reason:string;appliedAt?:string;createdAt:string};
export type ProfitLedgerEntry={id:string;marketplaceListingId:string;entryType:'expected_revenue'|'expected_cost'|'expected_fees'|'expected_margin'|'actual_revenue'|'actual_supplier_cost'|'actual_fees'|'shipping_cost'|'refund_cost'|'realized_profit';phase:'expected'|'actual';amountCents:number;currency:'EUR';calculationRule:string;evidenceType:string;evidenceId:string;occurredAt:string};
export const listMonitorableListings=()=>getWithParams<{items:MarketplaceListing[]}>('/v1/monitorable-listings');
export const listPriceRules=()=>getWithParams<{items:PriceRule[]}>('/v1/price-rules');
export const createPriceRule=(body:{name:string;minMarginBasisPoints:number;targetMarginBasisPoints:number;maxPriceCents?:number;maxDeltaCents:number;maxDeltaBasisPoints:number;cooldownSeconds:number;platformFeeBasisPoints:number;shippingCents:number;reserveCents:number;autoApply:boolean},key=newIdempotencyKey('price-rule'))=>command<PriceRule>('/v1/price-rules',body,key);
export const runMonitor=(body:{marketplaceListingId:string;priceRuleId:string;trigger:'manual'},key=newIdempotencyKey('monitor-run'))=>command<{run:{id:string;status:string};decision:PriceDecision}>(`/v1/monitor-runs`,body,key);
export const listPriceDecisions=(params?:{outcome?:PriceDecisionOutcome})=>getWithParams<{items:PriceDecision[]}>('/v1/price-decisions',params);
export const applyPriceDecision=(id:string,key=newIdempotencyKey('price-decision-apply'))=>command<PriceDecision>(`/v1/price-decisions/${encodeURIComponent(id)}/apply`,{},key);
export const getProfitReport=(params?:{from?:string;to?:string})=>getWithParams<{currency:'EUR';totals:Record<string,number>;items:ProfitLedgerEntry[]}>('/v1/profit/report',params);
export const formatEuroCents=(cents?:number)=>typeof cents==='number'?new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(cents/100):'—';
export function parseEuroInput(value:string):number|null{const normalized=value.trim().replace(/\s/g,'').replace(/\./g,'').replace(',','.');if(!/^\d+(?:\.\d{1,2})?$/.test(normalized))return null;const [euros,fraction='']=normalized.split('.');const cents=Number(euros)*100+Number(fraction.padEnd(2,'0'));return Number.isSafeInteger(cents)?cents:null;}
